App/urls.py
from django.urls import path, include
from .views import (lista_usuarios, lista_categorias, detalhe_usuarios,
                    criar_clientes, criar_interesse, criar_usuario, criar_categoria,
                    upload_avatar, sobre, perfil, editar_categoria, editar_interesse, editar_cliente, editar_usuario,
                    deletar_categoria, deletar_interesse, deletar_usuario)
from .views import produto_list_view, produto_create_view, produto_update_view, produto_delete_view, produto_detail_view
from django.contrib.auth import views as auth_views  
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('usuarios/', lista_usuarios, name = 'lista_usuarios'),
    path('usuarios/<int:usuario_id>/editar_usuario', editar_usuario, name = 'editar_usuario'),
    path('usuarios/<int:usuario_id>/deletar_usuario', deletar_usuario, name = 'deletar_usuario'),
    path('usuarios/<int:usuario_id>/detalhe_usuario/', detalhe_usuarios, name='detalhe_usuarios'),
    path('usuarios/<int:usuario_id>/criar_cliente', criar_clientes, name = 'criar_cliente'),
    path('usuarios/<int:usuario_id>/clientes/<int:cliente_id>/criar_interesse', criar_interesse, name='criar_interesse'),
    path('usuarios/<int:usuario_id>/clientes/<int:cliente_id>/editar_interesse/<int:interesse_id>/', editar_interesse, name='editar_interesse'),
    path('usuarios/<int:usuario_id>/clientes/<int:cliente_id>/deletar_interesse/<int:interesse_id>/', deletar_interesse, name='deletar_interesse'),
    path('usuarios/<int:usuario_id>/editar_cliente/<int:cliente_id>/', editar_cliente, name='editar_cliente'),
    path('criar_usuario', criar_usuario, name= 'criar_usuario'),
    path('criar_categoria', criar_categoria, name='criar_categoria'),
    path('lista_categorias', lista_categorias, name='lista_categorias'),
    path('categorias/<int:categoria_id>/deletar_categoria/', deletar_categoria, name='deletar_categoria'),
    path('editar_categoria/<int:categoria_id>/', editar_categoria, name='editar_categoria'),
    path('editar-avatar/', upload_avatar, name='editar_avatar'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('about/', sobre, name='sobre'),
    path('deletar_avatar/<int:avatar_id>/', perfil, name='deletar_avatar'),
    path('editar_avatar/<int:avatar_id>/', perfil, name='editar_avatar'),
    path('produtos/', produto_list_view.as_view(), name='lista_produtos_disponiveis'),
    path('criar_produto', produto_create_view.as_view(), name='criar_produto'),
    path('editar_produto/<int:produto_id>/', produto_update_view.as_view(), name='editar_produto'),
    path('produtos/<int:produto_id>/deletar_produto/', produto_delete_view.as_view(), name='deletar_produto'),
    path('produtos/<int:produto_id>/detalhe_produto/', produto_detail_view.as_view(), name='detalhe_produto'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SuaPrimeiraPagina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls')),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Usuario(AbstractUser): # Optei por fazer um usuário personalizado, para que eu possa usar os campos conforme minhas entregas antigas
    class TipoUsuario(models.TextChoices):
        administrador = 'A', 'Administrador'
        cliente = 'C', 'Cliente'
    tipo_usuario = models.CharField(max_length=1, choices=TipoUsuario.choices, default=TipoUsuario.cliente) # Tipo de usuário, padrão cliente
    # Não é necessário definir password e username, pois já estão definidos no AbstractUser

class Cliente(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE, primary_key=True, related_name='clientes') # cascade, vai deletar tudo que estiver associado, no caso os interesses
    nome = models.CharField(max_length=100)
    sobrenome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=11, unique=True) # CPF único, não pode ter dois iguais
    email = models.EmailField(max_length=50)
    data_nascimento = models.DateField()
    telefone = models.IntegerField()

class Categoria(models.Model):
    categoria = models.CharField(max_length=100)

    def __str__(self):
        return self.categoria  # Mostra o nome da categoria no dropdown

class Produto(models.Model):
    class Status(models.TextChoices):
        disponivel = 'D', 'Disponível'
        vendido = 'V', 'Vendido'
        reposicao = 'R', 'Reposição'
    produto = models.CharField(max_length=1000)
    descricao = models.CharField(max_length=1000)
    ano_fabricacao = models.IntegerField()
    nome_categoria = models.ForeignKey('Categoria', on_delete=models.PROTECT, related_name='produtos') # Protege a categoria, não deixa deletar se tiver produtos associados
    data_publicacao = models.DateTimeField(auto_now_add=True) # Adiciona a data de publicação automaticamente
    preco = models.DecimalField(max_digits=10, decimal_places=2) # Preço do produto, com 10 dígitos no total e 2 depois da vírgula
    status = models.CharField(max_length=1, choices=Status.choices, default=Status.disponivel)
    quantidade = models.IntegerField(default=1) # Quantidade do produto, padrão 1
    data_modificacao = models.DateTimeField(auto_now=True) # Adiciona a data de modificação automaticamente
    autor_modificacao = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True, blank=True)

class Interesse(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, related_name='interesses')
    interesse = models.CharField(max_length=100)

class Avatar(models.Model):
    Usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    imagem = models.ImageField(upload_to='avatares', null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.imagem}"

App/forms.py
from django import forms
from .models import Cliente, Interesse, Produto, Usuario, Avatar, Categoria
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.core.exceptions import ValidationError

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'sobrenome', 'cpf', 'email', 'telefone', 'data_nascimento']
        widgets = {
            'data_nascimento': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'})
        }

    # Para no editar perfil garantir que importou o form-control e deixar a formatação igual ao de criar usuário
    def __init__(self, *args, **kwargs):
        super(ClienteForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

class InteresseForm(forms.ModelForm):
    class Meta:
        model = Interesse
        fields = ['interesse']

class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['produto', 'descricao', 'ano_fabricacao', 'nome_categoria', 'preco', 'quantidade', 'status']

class PesquisaProdutoForm(forms.Form):
    termo = forms.CharField(
        label="Pesquisar Produto",
        max_length=100,
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite o nome do produto'})
    )

    categoria = forms.ModelChoiceField(
        queryset=Categoria.objects.all(),
        required=False,
        label='Categoria',
        empty_label="Todas as categorias"
    )
    status = forms.ChoiceField(
        choices=[('', 'Todos os status')] + list(Produto.Status.choices),
        required=False,
        label='Status'
    )

class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['username', 'password', 'tipo_usuario']

class RegistroUsuarioForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, required=True, label='Senha')
    password_confirm = forms.CharField(widget=forms.PasswordInput, required=True, label='Confirmar Senha')

    class Meta:
        model = Usuario
        fields = ['username', 'password']
        # Não considero tipo_usuario, pois ele já é definido no models com o valor padrão de cliente, também forço o valor em views.py
        labels = {
            'username': 'Nome',
            'password': 'Senha',
        }

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if Usuario.objects.filter(username=username).exists():
            raise ValidationError('Esse nome de usuário já existe.')
        return username
    
    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise ValidationError('A senha deve ter pelo menos 8 caracteres.')
        if not any(char.isdigit() for char in password):
            raise ValidationError('A senha deve conter pelo menos um número.')
        if not any(char.isupper() for char in password):
            raise ValidationError('A senha deve conter pelo menos uma letra maiúscula.')
        return password

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')

        if password != password_confirm:
            raise ValidationError('As senhas não coincidem.')
        return password_confirm

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['categoria']  

class AvatarForm(forms.ModelForm):
    class Meta:
        model = Avatar
        fields = ['imagem']

class UsuarioUpdateForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['username', 'tipo_usuario']
        labels = {
            'username': 'Usuário',
        }

    def __init__(self, *args, **kwargs):
        is_admin = kwargs.pop('is_admin', False)
        super().__init__(*args, **kwargs) 

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

        if not is_admin:
            self.fields['tipo_usuario'].widget = forms.HiddenInput()
    
    def clean_username(self):
        username = self.cleaned_data.get('username')
        usuario = Usuario.objects.filter(username=username)
        if self.instance:
            usuario = usuario.exclude(pk=self.instance.pk)
        if usuario.exists():
            raise ValidationError('Esse nome de usuário já existe.')
        return username

# Classe já é definida no Django, mas como não tem o label e o widget que eu quero, criei uma classe personalizada que sobrescreve a já existente
class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Senha Atual",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    new_password1 = forms.CharField(
        label="Nova Senha",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    new_password2 = forms.CharField(
        label="Confirme a Nova Senha",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.user.check_password(old_password):
            raise ValidationError('Senha atual incorreta.')
        return old_password

# Para o admin, não tem o campo de senha atual, apenas os dois novos
class AdminSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label="Nova Senha",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    new_password2 = forms.CharField(
        label="Confirme a Nova Senha",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

App/templates/App/confirmar_deletar_categoria.html
{% extends "base.html" %}

{% block title %}Confirmar exclusão categoria{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="card shadow-lg p-4">
            <h2 class="text-center mb-4">Você tem certeza que deseja deletar a categoria "{{ categoria.categoria }}"?</h2>

            <form method="post">
                {% csrf_token %}
                <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-danger btn-lg me-2">Deletar</button>
                    <a href="{% url 'lista_categorias' %}" class="btn btn-secondary btn-lg">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

App/templates/App/confirmar_deletar_produto.html
{% extends "base.html" %}

{% block title %}Confirmar exclusão produto{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="card shadow-lg p-4">
            <h2 class="text-center mb-4">Você tem certeza que deseja deletar o produto "{{ produto.produto }}"?</h2>

            <form method="post">
                {% csrf_token %}
                <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-danger btn-lg me-2">Deletar</button>
                    <a href="{% url 'lista_produtos_disponiveis' %}" class="btn btn-secondary btn-lg">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

App/templates/App/criar_interesse.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Novo Interesse{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Adicionar Interesse para {{ cliente.nome }}</h2>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="{{ form.interesse.id_for_label }}" class="form-label">Interesse</label>
            {{ form.interesse|add_class:"form-control" }}
        </div>
        <button type="submit" class="btn btn-success">Salvar</button>
        <a href="{% url 'detalhe_usuarios' usuario_id=cliente.usuario.pk %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

App/templates/App/criar_produto.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Dados Produto{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Inserir Produto</h2>
    <form method="POST" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="mb-3">
            <label for="{{ form.produto.id_for_label }}" class="form-label">Produto</label>
            {{ form.produto|add_class:"form-control" }}
        </div>
        <div class="mb-3">
            <label for="{{ form.descricao.id_for_label }}" class="form-label">Descrição</label>
            {{ form.descricao|add_class:"form-control" }}
        </div>
        <div class="mb-3">
            <label for="{{ form.ano_fabricacao.id_for_label }}" class="form-label">Ano Fabricação</label>
            {{ form.ano_fabricacao|add_class:"form-control" }}
        </div>
        <div class="mb-3">
            <label for="{{ form.preco.id_for_label }}" class="form-label">Valor</label>
            {{ form.preco|add_class:"form-control" }}
        </div>
        <div class="mb-3">
            <label for="{{ form.status.id_for_label }}" class="form-label">Status</label>
            {{ form.status|add_class:"form-select" }}
        </div>
        <div class="mb-3">
            <label for="{{ form.quantidade.id_for_label }}" class="form-label">Quantidade</label>
            {{ form.quantidade|add_class:"form-select" }}
        </div>
        <div class="mb-3">
            <label for="{{ form.nome_categoria.id_for_label }}" class="form-label">Categoria</label>
            {{ form.nome_categoria|add_class:"form-select" }}
        </div>

        <button type="submit" class="btn btn-primary">Salvar</button>
        <a href="{% url 'lista_produtos_disponiveis' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

App/templates/App/criar_usuario.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Dados Usuário{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Inserir Usuário</h2>
    {% if messages %}
        <div class="alert alert-success">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <form method="POST" class="needs-validation" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="alert alert-danger">
                {% for error in form.non_field_errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}

        <div class="mb-3">
            <label for="id_username" class="form-label">Usuário</label>
            {{ form.username|add_class:"form-control" }}
            <!-- Exibindo erros do campo de nome de usuário -->
            {% if form.username.errors %}
                <div class="text-danger">
                    {% for error in form.username.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
       
        <div class="mb-3">
            <label for="id_password" class="form-label">Senha</label>
            {{ form.password|add_class:"form-control" }}
            <small class="form-text text-muted">
                A senha deve ter pelo menos 8 caracteres, conter um número e uma letra maiúscula.
            </small>
            <!-- Exibindo erros do campo de senha -->
            {% if form.password.errors %}
                <div class="text-danger">
                    {% for error in form.password.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
       
        <div class="mb-3">
            <label for="id_password_confirm" class="form-label">Confirmar Senha</label>
            {{ form.password_confirm|add_class:"form-control" }}
            <!-- Exibindo erros do campo de confirmação de senha -->
            {% if form.password_confirm.errors %}
                <div class="text-danger">
                    {% for error in form.password_confirm.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        {% for field in form %}
            {% for error in field.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        {% endfor %}

        <button type="submit" class="btn btn-primary">Salvar</button>
        <a href="{% url 'lista_usuarios' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

App/templates/App/detalhe_produto.html
{% extends "base.html" %}

{% block title %}Detalhes do Produto{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="card shadow">
        <div class="card-body">
            <h2 class="card-title">{{ produto.produto }}</h2>

            <h3>Dados do Produto</h3>
            <p class="card-text"><strong>Descrição:</strong> {{ produto.descricao }}</p>
            <p class="card-text"><strong>Ano Fabricação:</strong> {{ produto.ano_fabricacao }}</p>
            <p class="card-text"><strong>Valor:</strong> R$ {{ produto.preco|floatformat:2 }}</p>
            <p class="card-text"><strong>Status:</strong>
                <span class="badge
                    {% if produto.status == 'D' %}bg-success
                    {% elif produto.status == 'V' %}bg-danger
                    {% elif produto.status == 'R' %}bg-secondary
                    {% endif %}">
                    {{ produto.get_status_display }}
                </span>
            </p>
            <p class="card-text"><strong>Categoria:</strong> {{ produto.nome_categoria }}</p>
            <p class="card-text"><strong>Data Cadastro:</strong> {{ produto.data_publicacao }}</p>

            {% if request.user.is_superuser %}
                <p class="card-text"><strong>Data Atualização:</strong> {{ produto.data_modificacao }}</p>
                <p class="card-text"><strong>Usuário:</strong> {{ produto.autor_modificacao }}</p>
            {% endif %}

            <!-- Botões alinhados -->
            <div class="d-flex gap-2 mt-3">
                {% if request.user.is_authenticated and request.user.is_superuser %}
                    <a href="{% url 'editar_produto' produto_id=produto.pk %}" class="btn btn-warning">Editar</a>
                {% endif %}
                <a href="{% url 'lista_produtos_disponiveis' %}" class="btn btn-primary">Voltar</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

App/templates/App/detalhe_usuario.html
{% extends "base.html" %}

{% block title %}Detalhes do Usuário{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="card shadow">
        <div class="card-body">
            <h2 class="card-title">{{ usuario.nome }}</h2>

            {% if cliente.usuario %}
                <hr>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <h3>Dados do Cliente</h3>
                    {% if request.user.is_authenticated and request.user.pk == usuario.pk %}
                        <div class="btn-group">
                            <a href="{% url 'editar_cliente' usuario_id=usuario.pk cliente_id=cliente.pk %}" class="btn btn-warning btn-sm">Editar</a>
                        </div>
                    {% endif %}
                </li>
                <p class="card-text"><strong>Email:</strong> {{ cliente.email }}</p>
                <p class="card-text"><strong>Telefone:</strong> {{ cliente.telefone }}</p>
                <p class="card-text"><strong>Data Nascimento:</strong> {{ cliente.data_nascimento|date:"d/m/Y" }}</p>

                {% if cliente.interesses.all %}
                    <p class="card-text"><strong>Interesses:</strong></p>
                    <ul class="list-group mb-3">
                        {% for interesse in cliente.interesses.all %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                {{ interesse.interesse }}
                                {% if request.user.is_authenticated and request.user.pk == usuario.pk %}
                                    <div class="btn-group">
                                        <a href="{% url 'editar_interesse' usuario_id=usuario.pk cliente_id=cliente.pk interesse_id=interesse.pk %}" class="btn btn-warning btn-sm">Editar</a>
                                        <a href="{% url 'deletar_interesse' usuario_id=usuario.pk cliente_id=cliente.pk interesse_id=interesse.pk %}" class="btn btn-danger btn-sm">Deletar</a>
                                    </div>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p class="alert alert-info">Nenhum interesse cadastrado para este cliente.</p>
                {% endif %}
            {% else %}
                <p class="alert alert-warning">Este usuário não possui um cliente associado!</p>
            {% endif %}

            <!-- Botões alinhados -->
            <div class="d-flex gap-2 mt-3">
                {% if cliente.usuario and request.user.pk == usuario.pk %}
                    <a href="{% url 'criar_interesse' usuario_id=usuario.pk cliente_id=cliente.pk %}" class="btn btn-success">Cadastrar Interesse</a>
                {% elif not cliente.usuario and request.user.pk == usuario.pk %}
                    <a href="{% url 'criar_cliente' usuario_id=usuario.pk %}" class="btn btn-success">Inserir Dados</a>
                {% endif %}
                <a href="{% url 'lista_usuarios' %}" class="btn btn-primary">Voltar</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

App/templates/App/editar_categoria.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Editar Categoria{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Editar Categoria</h2>
    <form method="POST" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="mb-3">
            <label for="{{ form.categoria.id_for_label }}" class="form-label">Categoria</label>
            {{ form.categoria|add_class:"form-control" }}
        </div>

        <button type="submit" class="btn btn-primary">Salvar</button>
        <a href="{% url 'lista_categorias' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

App/templates/App/editar_cliente.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Dados Cliente{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Editar Dados do Cliente</h2>
    <form method="POST" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="mb-3">
            <label for="{{ form.nome.id_for_label }}" class="form-label">Nome</label>
            {{ form.nome|add_class:"form-control" }}
        </div> 
        <div class="mb-3">
            <label for="{{ form.sobrenome.id_for_label }}" class="form-label">Sobrenome</label>
            {{ form.sobrenome|add_class:"form-control" }}
        </div>
        <div class="mb-3">
            <label for="{{ form.cpf.id_for_label }}" class="form-label">CPF</label>
            {{ form.cpf|add_class:"form-control" }}
        </div>
        <div class="mb-3">
            <label for="{{ form.data_nascimento.id_for_label }}" class="form-label">Data Nascimento</label>
            {{ form.data_nascimento|add_class:"form-control" }}
        </div>
        <div class="mb-3">
            <label for="{{ form.telefone.id_for_label }}" class="form-label">Telefone</label>
            {{ form.telefone|add_class:"form-control" }}
        </div>
        <div class="mb-3">
            <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
            {{ form.email|add_class:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
        <a href="{% url 'detalhe_usuarios' usuario_id=usuario_id %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

App/templates/App/editar_interesse.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Editar Interesse{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Editar Interesse</h2>
    <form method="POST" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="mb-3">
            <label for="{{ form.interesse.id_for_label }}" class="form-label">Interesse</label>
            {{ form.interesse|add_class:"form-control" }}
        </div>

        <button type="submit" class="btn btn-primary">Salvar</button>
        <a href="{% url 'detalhe_usuarios' usuario_id=usuario_id %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

App/templates/App/editar_produto.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Editar Produto{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Editar Produto</h2>
    <form method="POST" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="mb-3">
            <label for="{{ form.produto.id_for_label }}" class="form-label">Produto</label>
            {{ form.produto|add_class:"form-control" }}
        </div>
        <div class="mb-3">
            <label for="{{ form.descricao.id_for_label }}" class="form-label">Descrição</label>
            {{ form.descricao|add_class:"form-control" }}
        </div>
        <div class="mb-3">
            <label for="{{ form.ano_fabricacao.id_for_label }}" class="form-label">Ano Fabricação</label>
            {{ form.ano_fabricacao|add_class:"form-control" }}
        </div>
        <div class="mb-3">
            <label for="{{ form.preco.id_for_label }}" class="form-label">Valor</label>
            {{ form.preco|add_class:"form-control" }}
        </div>
        <div class="mb-3">
            <label for="{{ form.status.id_for_label }}" class="form-label">Status</label>
            {{ form.status|add_class:"form-select" }}
        </div>
        <div class="mb-3">
            <label for="{{ form.quantidade.id_for_label }}" class="form-label">Quantidade</label>
            {{ form.quantidade|add_class:"form-select" }}
        </div>
        <div class="mb-3">
            <label for="{{ form.nome_categoria.id_for_label }}" class="form-label">Categoria</label>
            {{ form.nome_categoria|add_class:"form-select" }}
        </div>

        <button type="submit" class="btn btn-primary">Salvar</button>
        <a href="{% url 'lista_produtos_disponiveis' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}